title: Abhinav Jain, PhD
logo: Abhinav2.png
description: Computational Biologist | Oncology | Immunology | Aging | Single Cell Multimodal | Spatial | Bulk Multiomics | Image Analysis | Population Genomics | ML | DL | Alumni UCSF, Mayo Clinic, IGIB
show_downloads: true
theme: jekyll-theme-minimal
