title: Abhinav Jain PhD
logo: Abhinav.jpg
description: Computational Biologist at Voyant Bio | Cancer | Immunology | Aging | Single Cell Multimodal | Spatial | Bulk Multiomics | Image Analysis | Population Genomics | Data Science | Alumni UCSF, Mayo Clinic, IGIB
show_downloads: true
theme: jekyll-theme-minimal
