title: Abhinav Jain, PhD
logo: Abhinav2.png
description: |
  9+ years experience as Computational Biologist | Oncology | Immunology | Aging | Single Cell Multimodal | Spatial | Bulk Multiomics | Image Analysis | Population Genomics | ML | DL.
  I am currently working at a start-up VoyantBio, San Francisco and research collaborator in UCSF and Mayo Clinic.
show_downloads: true
theme: jekyll-theme-minimal
